apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: project2
spec:
  selector:
    app: config-server
  ports:
    - name: http
      port: 8889
      targetPort: 8889
