apiVersion: v1
kind: Service
metadata:
  name: service-product
  namespace: project2
spec:
  selector:
    app: service-product
  ports:
    - name: http
      port: 8082
      targetPort: 8082
